### ISSUE TITLE
Something wrong with purgeCSS (seems it doesn't support pcss)

### ISSUE THREAD

**Issue by escapedoc** [nystudio107/annotated-webpack-4-config#10]
Ca not run the build from your example.
What have I done:
1. Cloned your repo
2. npm install
3. npm run build

Doesn't build anything:
![image](https://user-images.githubusercontent.com/36753884/50050936-36666080-0119-11e9-9add-5d805118f675.png)

**Comment by escapedoc** [comment]
The solution was uninstalling purgecss-webpack-plugin and purgecss-whitelister. Then installing pretty same versions as in package.json. 
Then another issue arises:
![image](https://user-images.githubusercontent.com/36753884/50051115-6adc1b80-011d-11e9-819e-d365a5412a68.png)

What could it be?
THe version of critical-css-webpack-plugin in current's repo is the newest as I can see in package.lock.json file

**Comment by khalwat** [comment]
Yeah that's correct, even though there was a PR included to support adding `.pcss` I think the parsers that it uses can't parse PostCSS properly.

You can use the PurgeCSS Whitelister on pure CSS files, or just come up with another way to whitelist entire files if they are PostCSS
