### ISSUE TITLE
Tailwind CSS imports are failing - No Configuration provided for ... preflight.css

### ISSUE THREAD

**Issue by bryanjhickey** [nystudio107/annotated-webpack-4-config#14]
Firstly, let me congratulate you on a such an awesome article and for making it available to the public! Webpack is a massive tool to try and learn in any comprehensive way and you have dug deep than many. Well done!

Now to the issue at hand, Tailwind imports in app.pcss are failing in the build process (as per screen shot).

![image](https://user-images.githubusercontent.com/538755/54600930-facd9080-4a91-11e9-9fce-fe64fa96f2c4.png)

Tailwindcss is installed as a dependency per original `package.json` with `yarn install`
I updated `.env`, `webpack.settings.js` and `twigpack.php` for my environment as per docs.
Built project with `yarn build` 
Imports are as per original `@import "tailwindcss/preflight";`

JS is compiling fine and confetti abounds but I have no tailwind styles available.

[Github repo](https://github.com/bryanjhickey/interpack-website)

**Comment by khalwat** [comment]
What version of Tailwind did you end up getting installed?

**Comment by robbue** [comment]
It worked for me after changing:
```
@import "tailwindcss/preflight";
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```
to:
```
@tailwind preflight;
@tailwind components;
@tailwind utilities;
```

**Comment by khalwat** [comment]
Thanks @robbue -- do you know in which version of Tailwind CSS this changed?

**Comment by khalwat** [comment]
So the `@import` syntax is apparently still what is recommended if we're using `postcss-loader` (and we are): 

https://next.tailwindcss.com/docs/installation/#2-add-tailwind-to-your-css

...but the issue you may be running into may be related to this:

https://stackoverflow.com/questions/46142717/css-loader-postcss-loader-module-build-failed-error-no-configuration-provide

**Comment by robbue** [comment]
Yes, it was the config that was not loading properly since I have changed the folder structure.

With the config.path it is working fine with `@import` and `tailwindcss@0.7.4`
```
loader: 'postcss-loader',
options: {
	config: {
		path: path.resolve(__dirname, './postcss.config.js')
	},
	sourceMap: true
}
```

Great work @khalwat!

**Comment by kristiansp** [comment]
I am having the same issue, but adding the path as suggested by @robbue doesn't change anything. It seems to actually find the config file, as if I set another path as a test, it gives the error `No PostCSS Config found in`. It also confirms that the path seems correct (I tried setting the path one level up, and the folder it then looked in is one above where the `postcss.config.js` resides.

Is there anything else I could try to get it working?

<img width="1086" alt="Screenshot 2019-09-21 at 12 36 14" src="https://user-images.githubusercontent.com/2248437/65372150-7213f500-dc6c-11e9-8704-91e383123079.png">

**Comment by TheDutchCoder** [comment]
Same issue here :( Setting the path doesn't seem to do anything.

**Comment by tom-c** [comment]
I've found that including a .stylelintrc file (can be empty, or used to control the whitelisting of units etc in your css) in the root of your project resolves it for me. No faff with paths config and using @import tailwind rules in my app.pcss. Hope that helps?

**Comment by TheDutchCoder** [comment]
I finally got this to work by just removing the stylelint plugin from the postcss-import config.

Adding an (empty) `.stylelintrc` file doesn't do anything for me, nor does setting the path.

It's too bad, but I don't think stylelint was really doing anything for me anyway :)

**Comment by masiorama** [comment]
I did the same as @TheDutchCoder , coz I did not find any workaround after trying for a while.

**Comment by khalwat** [comment]
I'm unable to reproduce this issue locally.

Have you folks who are experiencing it changed the directory structure in some way?
