### ISSUE TITLE
publicPath: settings.urls.publicPath() in webpack.common.js gives error

### ISSUE THREAD

**Issue by TomDeSmet** [nystudio107/annotated-webpack-4-config#16]
`publicPath: settings.urls.publicPath()` gives an error when running devmode.
Changing it to `publicPath: settings.urls.publicPath` solves it.

**Comment by khalwat** [comment]
That doesn't make sense... it is indeed a function

**Comment by TomDeSmet** [comment]
Sorry. There seems to be something wrong with the settings file when we pull from this report.
It still was set to '/' instead of the function.
