### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by Floriskoch** [nystudio107/annotated-webpack-4-config#19]
Would it be possible to output multiple css files using this setup? I would like to set up theme using the same components but using different SCSS/PCSS variables.

I have tried importing multiple `.pcss` files in `app.js` but that doesn't seem to work:

```
import "../stylesheets/theme1.pcss"
import "../stylesheets/theme2.pcss"
```

Any help would be greatly appreciated!

**Comment by khalwat** [comment]
Currently, no.
