### ISSUE TITLE
Duplicate files

### ISSUE THREAD

**Issue by thaoms** [nystudio107/annotated-webpack-4-config#2]
<img width="591" alt="screenshot 2018-11-13 23 19 10" src="https://user-images.githubusercontent.com/2323270/48446830-a68c6a00-e79a-11e8-8506-b10eef32353c.png">

I'm getting a duplicate files message when using this setup.
This makes it really slow in a homestead/vagrant/virtualbox setup. (1 cpu and 2048MB mem)

Saving css gives me a 9s-10s waiting time.

**Comment by khalwat** [comment]
What are the extra duplicate files?

**Comment by thaoms** [comment]
I actually did nothing extra on this setup, but it has something to do with Tailwind and postcss.

**Comment by TomDeSmet** [comment]
I have the same issue. Duplicate files for me are the confetti Vue component, a new custom Vue component I added in the same folder and the app.pcss.

![01](https://user-images.githubusercontent.com/16959207/50073604-64ab7500-01d9-11e9-8bdf-d5e23820aefa.JPG)
![02](https://user-images.githubusercontent.com/16959207/50073605-64ab7500-01d9-11e9-85fc-247954f027b2.JPG)

**Comment by khalwat** [comment]
This potentially is just the fact that we're doing dual builds of the same files, for the legacy as well as the modern bundles.
