### ISSUE TITLE
CPU boost by ignoring node_modules in dev server config

### ISSUE THREAD

**Issue by thaoms** [nystudio107/annotated-webpack-4-config#3]
I managed getting a huge cpu boost by adding the ignored prop in the dev server config,
and much faster compile times for css. (working with Vagrant and polling is 1)

```
watchOptions: {
  poll: !!parseInt(settings.devServerConfig.poll()),
  ignored: /node_modules/
},
```

see my pull request here #4

**Comment by khalwat** [comment]
Oh wow, I totally should have had that in, thank you!

**Comment by davilima6** [comment]
Hi, thanks for the great code. Have u experienced this problem with absolute imports (or is it mostly a create-react-app Windows-compatibility thing)?

https://github.com/facebook/create-react-app/blob/30ee52cf3b2cbb6ac70999c02b1196bcaba8d4ca/packages/react-scripts/config/webpackDevServer.config.js#L77
