### ISSUE TITLE
@babel/polyfill

### ISSUE THREAD

**Issue by fmal** [nystudio107/annotated-webpack-4-config#8]
`babel-preset-env` is configured with `useBuiltIns: 'entry'` and according to the docs (https://babeljs.io/docs/en/babel-preset-env) `import "@babel/polyfill"` line is expected in app's entry file, but i can't find it referenced anywhere (even as part of webpack entry points) in the project. Is it enough to add `@babel/polyfill` to dependencies in pkg.json?

**Comment by khalwat** [comment]
Yes, my understanding is that the runtime takes care of bundling this. It seems to be working as expected.

**Comment by lassemt** [comment]
While at it. Is there a way to load a polyfill that is not included with babel only in legacy?
