### ISSUE TITLE
Babel unexpected Token. - error in running app in simulator

### ISSUE THREAD

**Issue by ShaneLee11** [nystudio107/annotated-webpack-4-config#9]
Hi, I have just started on react and react-native. I have started writing an app skeleton but encounter a problem with firebase (or at least i think it is). or it is babel? 

I have reinstalled babel both globally and in the app folder.
I have tried to delete and reinstall firebase. but the program still doesnt run.
I have done a gradlew clean in the folder.
I am running on windows 10, and running android studio

![image](https://user-images.githubusercontent.com/45562614/49415182-d4206e00-f7b0-11e8-9c29-70f492ea35a3.png)
![image](https://user-images.githubusercontent.com/45562614/49415184-d682c800-f7b0-11e8-9a37-d08b5b10a677.png)

    import React, { Component } from 'react';
    import { Text, View } from 'react-native';
    import { Header, Button, Spinner } from './components/common';
    //import firebase from 'firebase';
    import LoginForm from './components/LoginForm';
    import HomeScreen from './components/HomeScreen';
    import firebase from '@firebase/app';
    import '@firebase/auth';

    class App extends Component {
      state = { loggedIn: null };

    componentDidMount() {
     firebase.initializeApp({
       apiKey: '******1f******',
       authDomain: 'auth-*****.firebaseapp.com',
        databaseURL: 'https://auth-****.firebaseio.com',
        projectId: 'auth-******',
       storageBucket: 'auth-******.appspot.com',
        messagingSenderId: '**********62*'
        });
       }

    firebase.auth().onAuthStateChanged((user) => {
         if (user) {
           this.setState({ loggedIn: true });
         } else {
           this.setState({ loggedIn: false });
         }
       });
     }

     renderContent() {
       switch (this.state.loggedIn) {
         case true:
           return (
             <HomeScreen />
            // <Button onPress={() => firebase.auth().signOut()}>
            //   Log Out
          //   </Button>
           );
         case false:
           return <LoginForm />;
         default:
           return <Spinner size="large" />;
       }
     }

     render() {
       const MainNavigator = StackNavigator({
         Home: { screen: HomeScreen }
       })
       return (
         <View>
           <Header headerText="Authentication" />
           {this.renderContent()}
         </View>
       );
     }
    }

    export default App;

**Comment by khalwat** [comment]
This seems unrelated to the webpack config
